---
title: Visual Dashboard for Real-Time Analysis of Social Media
author:
  - name: Huang Linya
    email: linya.huang.2020@smu.edu.sg
    affiliation: Singapore Management University
  - name: Lim Jiahui
    email: jiahui.lim.2020@smu.edu.sg
    affiliation: Singapore Management University
  - name: Zhang Ying
    email: ying.zhang.2020@smu.edu.sg
    affiliation: Singapore Management University   
abstract: |
  This is the abstract.

  It consists of two paragraphs.
bibliography: sigproc.bib
csl: acm-sig-proceedings.csl
output: rticles::acm_article
---



# Introduction 

Detecting abnormal events ,such as disaster or crisis, from microblog social media has become a trend, as social media has played a pervasive role in the way people behave and think. Nowadays, people are also using time-stamped , geo -located data to share live information about what’s happening in their surroundings, which enables the public, government and researches to sense abnormal events in community more quickly and take immediate actions.

To better analyzing and visualizing social media texts,  several text analytics techniques can be applied, such as wordcloud, topic modeling, network analysis, geospail analysis and so on. In real-world practices, researchers has built various social media text visualization in different domain and lack of an integrated visualization.

In order to build a comprehend visualization dashboard with an interactive user interface, we buit the application based on R shiny - a web application framework to create interactive web applications - and text analytical R packages. 

This paper reports our research and development effort to the real-time social media microblog analysis. It consists of XXX sections. Section 1 provides a general introduction of the paper, followed by a motivation and objectives of the paper. Section 3 provides a literature review of related analytical techniques and Section 4 provides the discussion of analytical methods applied in our analysis and development. Then we will discuss the user interface and application design and provides examples of analysis flow. Lastly, the paper concludes with consideration of future improvement work.


# Motivation and Objectives

Our research are motivated by the lack of integrated and comprehensive real-time social-media dashboard. We amis to apply appropriate text analytics method and visually driven data analysis techniques to provide a handy analytic tools to help users understand the social-media posting through various approaches,

1) Exploratory Data Analysis (EDA) and Time-series Analysis by basic statistical and world cloud visualization, which will provide a overview of content being discussed and help to highlight past events that occurred at certain areas;

2) Topic Modeling techniques by Latent Dirichlet Allocation algorithm will be performed to understand topics generated from text data. And  topic trend and user engagement of each topic will be provided to understand the trend and public response to the topic;

3) Network Analysis will be performed based on the re-tweet relationship between users to discover influential authors. We will also analysis the various centrality methods of the network and their distributions to help users explore and identify social relationships, interactions, and communications;

4) Hexagon Binning Map discussed in research paper (Kam,BARSHIKAR,TAN 2012) will be applied to show real-time location-stamped text distribution in the community. By visualizing color with gradient, users can quickly locate the hexagon districts with the posts information and subsequently estimate the risk level in specific areas.

# Literature Review







# Analytical Methods


# User Interface and Application Design

# Results Analysis

# Conclusion and Future Work



# References

---
references:
- id: meier2012
  title: Professinal Android 4 Application Development
  author: 
  - family: Meier
    given: Reto
  type: book
  publisher: John Wiley & Sons, Inc.
  issued:
    year: 2012
    month: 5
- id: fenner2012a
  title: One-click science marketing
  author:
  - family: Fenner
    given: Martin
  container-title: Nature Materials
  volume: 11
  URL: 'https://doi.org/10.1038/nmat3283'
  DOI: 10.1038/nmat3283
  issue: 4
  publisher: Nature Publishing Group
  page: 261-263
  type: article-journal
  issued:
    year: 2012
    month: 3
...

